Create updates directory on start

diff --git a/scripts/bismark-passive b/scripts/bismark-passive
--- a/scripts/bismark-passive
+++ b/scripts/bismark-passive
@@ -3,6 +3,12 @@
 EXE="bismark-passive.bin"
 IFACE="br-lan"
 DELAY=3
+UPDATES_DIR=/tmp/bismark-passive/updates
+
+if ! mkdir -p $UPDATES_DIR; then
+    echo "Unable to create $UPDATES_DIR"
+    exit 1
+fi
 
 while [ 1 ]; do
   echo "Starting Bismark Passive"
